# when generating a new artifact, add the new feather file to the datasets folder in Arrow format at
# https://osf.io/djaqb/, then download that folder to generate the tarball
# (so that we don't forget datasets)

[TestData]
# compute this using
# using Tar, Inflate, SHA
# filename = "download?version=9" # I just used wget for the URL below and this is how it saved it
# println("sha256 = \"", bytes2hex(open(sha256, filename)), "\"")
# println("git-tree-sha1 = \"", Tar.tree_hash(IOBuffer(inflate_gzip(filename))), "\"")
# from https://julialang.github.io/Pkg.jl/dev/artifacts/
git-tree-sha1 = "6d31be16850ffb7b5c0b80cb25f85b5c10df6546"
lazy = true

    [[TestData.download]]
    # this is the SHA from https://osf.io/djaqb/download?version=9
    sha256 = "86de0984a920604d27bf5d9c1031bb65b9cb960c2450c064b7fcd29a052bbd34"
    # when updating this, make sure to change to change the version number,
    # because if the version number isn't included, it will always point to the
    # latest version, which means it will break existing users when we update
    # between releases.
    url = "https://osf.io/djaqb/download?version=9"

    # for future work on using xz-compressed data:
    # Julia invokes wget without using HTTP metadata, so we need the link
    # to end with the right extension unless we want to fall back to gzip compression
