[TestData]
git-tree-sha1 = "8e1cb0be00e404a4a5e162bddc1d0235cc720ece"
lazy = true

    [[TestData.download]]
    sha256 = "c4b979ef93a10a6517eebf88d660500ff47ac1586e9cc897e4d10ffaa6378eb2"
    # when updating this, making sure to include the version (change to new) and
    # displayName (don't change) because the default link always points to the newest
    # (and so will not match the SHA for users not yet on the most recent version)
    # and Julia invokes wget without using HTTP metadata, so we need the link
    # to end with the right extension unless we want to fall back to gzip compression
    url = "https://osf.io/pcjk6/download"
