# when generating a new artifact, add the new feather file to the datasets folder at
# https://osf.io/a94tr/, then download that folder to generate the tarball
# (so that we don't forget datasets)

[TestData]
# compute this using
# using Tar, Inflate, SHA
# filename = "download?version=2" # I just used wget for the URL below and this is how it saved it
# println("sha256: ", bytes2hex(open(sha256, filename)))
# println("git-tree-sha1: ", Tar.tree_hash(IOBuffer(inflate_gzip(filename))))
# from https://julialang.github.io/Pkg.jl/dev/artifacts/
git-tree-sha1 = "a3955a5f747d01e628944b1031b44e31f027ebef"
lazy = true

    [[TestData.download]]
    # this is the SHA from https://osf.io/djaqb/download?version=2
    sha256 = "b6273f0cfeb5b12e2afede33de6d68a8d926e7b684cf071c7622f1e6ef7aa64a"
    # when updating this, make sure to change to change the version number,
    # because if the version number isn't included, it will always point to the
    # latest version, which means it will break existing users when we update
    # between releases.
    url = "https://osf.io/djaqb/download?version=2"

    # for future work on using xz-compressed data:
    # Julia invokes wget without using HTTP metadata, so we need the link
    # to end with the right extension unless we want to fall back to gzip compression
