# when generating a new artifact, add the new feather file to the datasets folder at
# https://osf.io/a94tr/, then download that folder to generate the tarball
# (so that we don't forget datasets)

[TestData]
# this is black magic to compute. Just let it error and copy over the new value.
git-tree-sha1 = "4d1410cd290622e426411273ef379fe82b749ca4"
lazy = true

    [[TestData.download]]
    # this is the SHA from https://osf.io/pcjk6/?show=revision
    sha256 = "b66369456c0ec9d1490d61d0c0686999e6422051295aeb9e14ab27693ccaec54"
    # when updating this, make sure to change to change the version number,
    # because if the version number isn't included, it will always point to the
    # latest version, which means it will break existing users when we update
    # between releases.
    url = "https://osf.io/pcjk6/download?version=4"

    # for future work on using xz-compressed data:
    # Julia invokes wget without using HTTP metadata, so we need the link
    # to end with the right extension unless we want to fall back to gzip compression
