# when generating a new artifact, add the new feather file to the datasets folder at
# https://osf.io/a94tr/, then download that folder to generate the tarball
# (so that we don't forget datasets)

[TestData]
# compute this using
# using Tar, Inflate, SHA
# filename = "download?version=4" # I just used wget for the URL below and this is how it saved it
# println("sha256: ", bytes2hex(open(sha256, filename)))
# println("git-tree-sha1: ", Tar.tree_hash(IOBuffer(inflate_gzip(filename))))
# from https://julialang.github.io/Pkg.jl/dev/artifacts/
git-tree-sha1 = "395c2dcaef75d1f15c9842e003b84e1c0b1a1e64"
lazy = true

    [[TestData.download]]
    # this is the SHA from https://osf.io/djaqb/download?version=1
    sha256 = "f31567e1775f7d0858dcf302158ad16635a86628e00968627aa2fb753b009f95"
    # when updating this, make sure to change to change the version number,
    # because if the version number isn't included, it will always point to the
    # latest version, which means it will break existing users when we update
    # between releases.
    url = "https://osf.io/djaqb/download?version=1"

    # for future work on using xz-compressed data:
    # Julia invokes wget without using HTTP metadata, so we need the link
    # to end with the right extension unless we want to fall back to gzip compression
