# when it's time to update the data agin, this code snippet will help:
# using Pkg.Artifacts
# import Base.Filesystem.cp
# datasets = "/home/phillip/Desktop/datasets/"
# create_artifact() do artifact_dir
#   for f in readdir(datasets)
#       cp(joinpath(datasets,f), joinpath(artifact_dir,f))
#   end
# end
# the returned sha is the git-tree-sha1
# osf will show the tarball's sha256 in the revisions page for the current version

[TestData]
git-tree-sha1 = "bf65e73c846c30aa5ec8bcb0443d12ffe1456671"
lazy = true

    [[TestData.download]]
    sha256 = "24b1778f89c8b9f809d3f372bda50b4944eeb3ad9a993379c81170768c8907af"
    url = "https://osf.io/pcjk6/download"
