"""
    MultimembershipReMat{T,S} <: AbstractReMat{T}

A section of a model matrix generated by a random-effects term for a
multimembership grouping factor, i.e. one where each observation may be
associated with several (weighted) levels of the grouping factor.

Unlike [`ReMat`](@ref), there is no `refs` field: the association between
observations and levels is encoded entirely in the sparse `adjA` field,
which may have any number of nonzero blocks per observation (column).

# Fields
- `trm`: the grouping factor as a `StatsModels.CategoricalTerm`
  (a synthetic term for the membership pseudo-variable; only its symbol is meaningful)
- `levels`: the levels of the grouping factor
- `cnames`: the names of the columns of the model matrix generated by the left-hand side of the term
- `z`: transpose of the model matrix generated by the left-hand side of the term
- `wtz`: a weighted copy of `z` (`z` and `wtz` are the same object for unweighted cases)
- `λ`: a `LowerTriangular` or `Diagonal` matrix of size `S×S`
- `inds`: a `Vector{Int}` of linear indices of the potential nonzeros in `λ`
- `adjA`: the adjoint of the matrix as a `SparseMatrixCSC{T}`, i.e. the
  Khatri-Rao product of the membership weights matrix and `z`
- `wtadjA`: a weighted copy of `adjA` (`adjA` and `wtadjA` are the same object for unweighted cases)
- `scratch`: a `Matrix{T}`
"""
mutable struct MultimembershipReMat{T,S} <: AbstractReMat{T}
    trm::Any
    levels::Any
    cnames::Vector{String}
    z::Matrix{T}
    wtz::Matrix{T}
    λ::Union{LowerTriangular{T,Matrix{T}},Diagonal{T,Vector{T}}}
    inds::Vector{Int}
    adjA::SparseMatrixCSC{T,Int32}
    wtadjA::SparseMatrixCSC{T,Int32}
    scratch::Matrix{T}
end

ismultimember(::AbstractReMat) = false
ismultimember(::MultimembershipReMat) = true

Base.size(A::MultimembershipReMat) = reverse(size(A.adjA))

SparseArrays.sparse(A::MultimembershipReMat) = adjoint(A.adjA)

Base.getindex(A::MultimembershipReMat, i::Integer, j::Integer) = getindex(A.adjA, j, i)

nranef(A::MultimembershipReMat) = size(A.adjA, 1)

LinearAlgebra.cond(A::MultimembershipReMat) = cond(A.λ)

fname(A::MultimembershipReMat) = fname(A.trm)

getθ(A::MultimembershipReMat{T}) where {T} = getθ!(Vector{T}(undef, nθ(A)), A)

function getθ!(v::AbstractVector{T}, A::MultimembershipReMat{T}) where {T}
    length(v) == length(A.inds) || throw(DimensionMismatch("length(v) ≠ length(A.inds)"))
    m = A.λ
    @inbounds for (j, ind) in enumerate(A.inds)
        v[j] = m[ind]
    end
    return v
end

# all levels are always considered present: they are user-specified
# via the membership matrix instead of being inferred from the data
DataAPI.levels(A::MultimembershipReMat) = A.levels

indmat(::MultimembershipReMat{T,1}) where {T} = ones(Bool, 1, 1)
function indmat(rt::MultimembershipReMat{T,S}) where {T,S}
    return reshape([i in rt.inds for i in 1:abs2(S)], S, S)
end

nlevs(A::MultimembershipReMat) = length(A.levels)

nθ(A::MultimembershipReMat) = length(A.inds)

function lowerbd(A::MultimembershipReMat{T}) where {T}
    return fill!(similar(A.inds, T), -Inf)
end

StatsModels.isnested(::MultimembershipReMat, ::AbstractReMat) = false
StatsModels.isnested(::AbstractReMat, ::MultimembershipReMat) = false
StatsModels.isnested(::MultimembershipReMat, ::MultimembershipReMat) = false

LinearAlgebra.Matrix(A::MultimembershipReMat) = Matrix(sparse(A))

function PCA(A::MultimembershipReMat{T,1}; corr::Bool=true) where {T}
    val = ones(T, 1, 1)
    return PCA(corr ? val : abs(only(A.λ)) * val, A.cnames; corr=corr)
end

function PCA(A::MultimembershipReMat{T,S}; corr::Bool=true) where {T,S}
    return PCA(A.λ, A.cnames; corr=corr)
end

DataAPI.refpool(A::MultimembershipReMat) = A.levels

DataAPI.refvalue(A::MultimembershipReMat, i::Integer) = A.levels[i]

function Base.copy(ret::MultimembershipReMat{T,S}) where {T,S}
    return MultimembershipReMat{T,S}(ret.trm,
        ret.levels,
        ret.cnames,
        ret.z,
        ret.wtz,
        copy(ret.λ),
        ret.inds,
        ret.adjA,
        ret.wtadjA,
        copy(ret.scratch))
end

function LinearAlgebra.copy_oftype(A::MultimembershipReMat{<:Any,S}, ::Type{T}) where {T,S}
    return MultimembershipReMat{T,S}(
        A.trm,
        A.levels,
        A.cnames,
        LinearAlgebra.copy_oftype(A.z, T),
        LinearAlgebra.copy_oftype(A.wtz, T),
        LinearAlgebra.copy_oftype(A.λ, T),
        A.inds,
        LinearAlgebra.copy_oftype(A.adjA, T),
        LinearAlgebra.copy_oftype(A.wtadjA, T),
        LinearAlgebra.copy_oftype(A.scratch, T),
    )
end

function reweight!(A::MultimembershipReMat{T}, sqrtwts::Vector) where {T}
    if length(sqrtwts) > 0
        if A.z === A.wtz
            A.wtz = similar(A.z)
            A.wtadjA = copy(A.adjA)
        end
        mul!(A.wtz, A.z, Diagonal(sqrtwts))
        anz = nonzeros(A.adjA)
        wnz = nonzeros(A.wtadjA)
        @inbounds for j in axes(A.adjA, 2)
            for k in nzrange(A.adjA, j)
                wnz[k] = anz[k] * sqrtwts[j]
            end
        end
    end
    return A
end

function lmulΛ!(adjA::Adjoint{T,<:MultimembershipReMat{T,1}}, B::Matrix{T}) where {T}
    return lmul!(only(parent(adjA).λ), B)
end

function lmulΛ!(adjA::Adjoint{T,<:MultimembershipReMat{T,S}}, B::VecOrMat{T}) where {T,S}
    lmul!(adjoint(parent(adjA).λ), reshape(B, S, :))
    return B
end

function rmulΛ!(A::Matrix{T}, B::MultimembershipReMat{T,1}) where {T}
    return rmul!(A, only(B.λ))
end

function rmulΛ!(A::Matrix{T}, B::MultimembershipReMat{T,S}) where {T,S}
    m, n = size(A)
    q, r = divrem(n, S)
    iszero(r) || throw(DimensionMismatch("size(A, 2) is not a multiple of block size"))
    λ = B.λ
    for k in 1:q
        coloffset = (k - 1) * S
        rmul!(view(A, :, (coloffset + 1):(coloffset + S)), λ)
    end
    return A
end

# Z'Z for a multimembership term has general symmetric fill,
# so Λ'AΛ + I must operate on all S×S tiles, not only the diagonal ones.
# Λ = I ⊗ λ acts on each tile separately, so scale all block columns by λ
# on the right, then all block rows by λ' on the left.
function copyscaleinflate!(
    Ljj::Matrix{T}, Ajj::Matrix{T}, Λj::MultimembershipReMat{T,1}
) where {T}
    lambsq = abs2(only(Λj.λ))
    @inbounds for i in eachindex(Ljj, Ajj)
        Ljj[i] = lambsq * Ajj[i]
    end
    @inbounds for i in diagind(Ljj)
        Ljj[i] += one(T)
    end
    return Ljj
end

function copyscaleinflate!(
    Ljj::Matrix{T}, Ajj::Matrix{T}, Λj::MultimembershipReMat{T,S}
) where {T,S}
    n = LinearAlgebra.checksquare(Ljj)
    iszero(rem(n, S)) ||
        throw(DimensionMismatch("size(Ljj, 1) is not a multiple of S"))
    copyto!(Ljj, Ajj)
    rmulΛ!(Ljj, Λj)
    lmulΛ!(Λj', Ljj)
    @inbounds for k in diagind(Ljj)
        Ljj[k] += one(T)
    end
    return Ljj
end

function LinearAlgebra.mul!(
    C::Matrix{T}, adjA::Adjoint{T,<:MultimembershipReMat{T}}, B::MultimembershipReMat{T}
) where {T}
    Aa = parent(adjA).wtadjA
    Ba = B.wtadjA
    size(C) == (size(Aa, 1), size(Ba, 1)) && size(Aa, 2) == size(Ba, 2) ||
        throw(DimensionMismatch(""))
    fill!(C, zero(T))
    Arv = rowvals(Aa)
    Anz = nonzeros(Aa)
    Brv = rowvals(Ba)
    Bnz = nonzeros(Ba)
    @inbounds for j in axes(Aa, 2)
        for ka in nzrange(Aa, j)
            i = Arv[ka]
            v = Anz[ka]
            for kb in nzrange(Ba, j)
                C[i, Brv[kb]] = muladd(v, Bnz[kb], C[i, Brv[kb]])
            end
        end
    end
    return C
end

function LinearAlgebra.mul!(
    C::Matrix{T}, adjA::Adjoint{T,<:MultimembershipReMat{T}}, B::ReMat{T,P}
) where {T,P}
    Aa = parent(adjA).wtadjA
    size(C) == (size(Aa, 1), nranef(B)) && size(Aa, 2) == size(B, 1) ||
        throw(DimensionMismatch(""))
    fill!(C, zero(T))
    rv = rowvals(Aa)
    nz = nonzeros(Aa)
    Bwt = B.wtz
    @inbounds for (j, r) in enumerate(B.refs)
        joffset = (r - 1) * P
        for k in nzrange(Aa, j)
            i = rv[k]
            v = nz[k]
            for p in 1:P
                C[i, joffset + p] = muladd(v, Bwt[p, j], C[i, joffset + p])
            end
        end
    end
    return C
end

function Base.:(*)(
    adjA::Adjoint{T,<:MultimembershipReMat{T}}, B::AbstractReMat{T}
) where {T}
    return mul!(Matrix{T}(undef, nranef(parent(adjA)), nranef(B)), adjA, B)
end

function Base.:(*)(adjA::Adjoint{T,<:ReMat{T}}, B::MultimembershipReMat{T}) where {T}
    throw(ArgumentError(
        "multimembership terms must be sorted after single-membership terms"
    ))
end

function LinearAlgebra.mul!(
    C::Matrix{T},
    adjA::Adjoint{T,<:FeMat{T}},
    B::MultimembershipReMat{T},
    α::Number,
    β::Number,
) where {T}
    Awt = parent(adjA).wtxy
    Ba = B.wtadjA
    n, p = size(Awt)
    size(C) == (p, size(Ba, 1)) && size(Ba, 2) == n || throw(DimensionMismatch(""))
    isone(β) || rmul!(C, β)
    rv = rowvals(Ba)
    nz = nonzeros(Ba)
    @inbounds for j in axes(Ba, 2)
        for k in nzrange(Ba, j)
            r = rv[k]
            αv = α * nz[k]
            for i in 1:p
                C[i, r] = muladd(αv, Awt[j, i], C[i, r])
            end
        end
    end
    return C
end

function Base.:(*)(adjA::Adjoint{T,<:FeMat{T}}, B::MultimembershipReMat{T}) where {T}
    # true/false instead of one(T)/zero(T): false is a strong zero,
    # so NaNs in the undef array are overwritten instead of propagated
    return mul!(
        Matrix{T}(undef, size(parent(adjA), 2), nranef(B)), adjA, B, true, false
    )
end

function LinearAlgebra.mul!(
    y::AbstractVector{<:Union{T,Missing}},
    A::MultimembershipReMat{T},
    b::AbstractVector{<:Union{T,Missing}},
    alpha::Number,
    beta::Number,
) where {T}
    Aa = A.adjA
    length(y) == size(Aa, 2) && length(b) == size(Aa, 1) ||
        throw(DimensionMismatch(""))
    isone(beta) || rmul!(y, beta)
    rv = rowvals(Aa)
    nz = nonzeros(Aa)
    @inbounds for j in axes(Aa, 2)
        for k in nzrange(Aa, j)
            # must be muladd and not fma because of potential missings
            y[j] = muladd(alpha * b[rv[k]], nz[k], y[j])
        end
    end
    return y
end

function LinearAlgebra.mul!(
    y::AbstractVector{<:Union{T,Missing}},
    A::MultimembershipReMat{T,S},
    B::AbstractMatrix{<:Union{T,Missing}},
    alpha::Number,
    beta::Number,
) where {T,S}
    Aa = A.adjA
    length(y) == size(Aa, 2) && size(B) == (S, nlevs(A)) ||
        throw(DimensionMismatch(""))
    isone(beta) || rmul!(y, beta)
    rv = rowvals(Aa)
    nz = nonzeros(Aa)
    @inbounds for j in axes(Aa, 2)
        for k in nzrange(Aa, j)
            r = rv[k]
            # must be muladd and not fma because of potential missings
            y[j] = muladd(alpha * B[mod1(r, S), fld1(r, S)], nz[k], y[j])
        end
    end
    return y
end

rowlengths(A::MultimembershipReMat{T,1}) where {T} = vec(abs.(A.λ.data))

function rowlengths(A::MultimembershipReMat)
    ld = A.λ
    return if isa(ld, Diagonal)
        abs.(ld.diag)
    else
        [norm(view(ld, i, 1:i)) for i in 1:size(ld, 1)]
    end
end

function setθ!(A::MultimembershipReMat{T}, v::AbstractVector{T}) where {T}
    A.λ.data[A.inds] = v
    return A
end

σvals(A::MultimembershipReMat{T,1}, sc::Number) where {T} = (sc * abs(only(A.λ.data)),)

σvals(A::MultimembershipReMat, sc::Number) = σvals(A.λ, sc)

σvals!(v::AbstractVector, A::MultimembershipReMat, sc::Number) = σvals!(v, A.λ, sc)

function σvals!(v::AbstractVector{T}, A::MultimembershipReMat{T,1}, sc::Number) where {T}
    isone(length(v)) || throw(DimensionMismatch("length(v) = $(length(v)), should be 1"))
    @inbounds v[1] = sc * abs(only(A.λ.data))
    return v
end

function σs(A::MultimembershipReMat{T,1}, sc::Number) where {T}
    return NamedTuple{(Symbol(only(A.cnames)),)}(σvals(A, sc))
end

function σs(A::MultimembershipReMat{T}, sc::Number) where {T}
    return NamedTuple{(Symbol.(A.cnames)...,)}(σvals(A.λ, sc))
end

function σρs(A::MultimembershipReMat{T,1}, sc::T) where {T}
    return NamedTuple{(:σ, :ρ)}((
        NamedTuple{(Symbol(only(A.cnames)),)}((sc * abs(only(A.λ)),)), ()
    ))
end

function σρs(A::MultimembershipReMat{T}, sc::T) where {T}
    return _σρs(A.λ, sc, indmat(A), Symbol.(A.cnames))
end

function corrmat(A::MultimembershipReMat{T}) where {T}
    λ = A.λ
    λnorm = rownormalize!(copy!(zeros(T, size(λ)), λ))
    return Symmetric(λnorm * λnorm', :L)
end

vsize(::MultimembershipReMat{T,S}) where {T,S} = S

function zerocorr!(A::MultimembershipReMat{T}) where {T}
    λ = A.λ = Diagonal(A.λ)
    k = size(λ, 1)
    A.inds = intersect(A.inds, range(1; step=k + 1, length=k))
    return A
end
