name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
  release:
    types:
      - created

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3, 1.4]
        julia-arch: [x64, x86]
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        exclude:
          - os: macos-10.15
            julia-arch: x86
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
        - if contains(steps.julia-version, 1.4) && continue-on-error = true
      - uses: julia-actions/julia-runtest@latest
        - if contains(steps.julia-version, 1.4) && continue-on-error = true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: julia-actions/julia-uploadcodecov@latest
        if: success() && startsWith(steps.os, 'Ubuntu 18.04') && contains(steps.julia-version, 1.3)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - uses: julia-actions/julia-docdeploy@releases/v1
        if: success() && startsWith(steps.os, 'Ubuntu 18.04') && contains(steps.julia-version, 1.3)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
