name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
  release:
    types:
      - created
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3]
        julia-arch: [x64]
        os: [ubuntu-18.04, macos-10.15, windows-2019]
      matrix:
        fail-fast: false
        julia-version: [1.3, 1.4.1-rc1]
        julia-arch: [x64, x86]
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        exclude:
          - julia-version: 1.3
            julia-arch: x64
          - os: macos-10.15
            julia-arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v0.1
      - uses: julia-actions/julia-runtest@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: julia-actions/julia-uploadcodecov@v0.1
        if: startsWith(job.os, 'Ubuntu 18.04')
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - uses: julia-actions/julia-docdeploy@releases/v1
        if: startsWith(job.os, 'Ubuntu 18.04')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
  allow_failures:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1.3, 1.4]
        julia-arch: [x64, x86]
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        exclude:
          - julia-version: 1.3
            julia-arch: x64
          - os: macos-10.15
            julia-arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v0.1
      - uses: julia-actions/julia-runtest@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
