name: Future
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: false
      matrix:
        julia-version: [nightly]
        julia-arch: [x64]
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v0.1
      - uses: julia-actions/julia-runtest@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # OPENBLAS_CORETYPE: haswell
