name: "minimum compat"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.8]
        julia-arch: [x64]
        os: [ubuntu-18.04, macos-11, windows-2019]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v0.1
      - uses: julia-actions/julia-runtest@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: julia-actions/julia-uploadcodecov@v0.1
