name: Tier 1
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.4,1.5]
        julia-arch: [x64]
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v0.1
      - uses: julia-actions/julia-runtest@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: julia-actions/julia-uploadcodecov@v0.1
        if:  ${{ startsWith(matrix.os, 'Ubuntu') && startsWith(matrix.julia-version, '1.5') }}
